[2025-05-27T22:12:13.308+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-25T00:00:00+00:00 [queued]>
[2025-05-27T22:12:13.331+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-25T00:00:00+00:00 [queued]>
[2025-05-27T22:12:13.332+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-27T22:12:13.369+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_facts.validate_contacts> on 2025-05-25 00:00:00+00:00
[2025-05-27T22:12:13.386+0000] {standard_task_runner.py:60} INFO - Started process 1511 to run task
[2025-05-27T22:12:13.420+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'validate_facts.validate_contacts', 'manual__2025-05-25T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmpvt3_w5ge']
[2025-05-27T22:12:13.443+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask validate_facts.validate_contacts
[2025-05-27T22:12:13.635+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-25T00:00:00+00:00 [running]> on host 485388d78c3d
[2025-05-27T22:12:13.955+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='validate_facts.validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T00:00:00+00:00'
[2025-05-27T22:12:13.965+0000] {Marketing_Data_Pipeline.py:39} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-27T22:12:15.045+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | schema_format = PASS
[2025-05-27T22:12:15.394+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | freshness = PASS
[2025-05-27T22:12:15.662+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | row_count = PASS
[2025-05-27T22:12:15.853+0000] {data_validation.py:128} INFO - Valid Data for contacts_2025-05-25.csv created in /opt/***/data/validated_data
[2025-05-27T22:12:15.863+0000] {data_validation.py:144} INFO - Removed /opt/***/data/raw_data/contacts_2025-05-25.csv from raw_data folder
[2025-05-27T22:12:16.233+0000] {metadata.py:164} INFO - üîë Logged DQ signature for contacts_2025-05-25.csv: 
[2025-05-27T22:12:16.846+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | contacts = PASS
[2025-05-27T22:12:17.284+0000] {metadata.py:109} INFO - üìù Logged stage 'validated' for contacts_2025-05-25.csv at 2025-05-27T22:12:16.854414
[2025-05-27T22:12:17.291+0000] {utils.py:56} INFO - task_metrics
[2025-05-27T22:12:17.296+0000] {Marketing_Data_Pipeline.py:41} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-27T22:12:17.299+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-27T22:12:17.336+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Marketing_Data_Pipeline, task_id=validate_facts.validate_contacts, execution_date=20250525T000000, start_date=20250527T221213, end_date=20250527T221217
[2025-05-27T22:12:17.439+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-27T22:12:17.662+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
