[2025-05-24T09:17:52.586+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_form_fills manual__2025-05-24T09:17:05.548015+00:00 [queued]>
[2025-05-24T09:17:53.244+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_form_fills manual__2025-05-24T09:17:05.548015+00:00 [queued]>
[2025-05-24T09:17:53.247+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T09:17:53.427+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_form_fills> on 2025-05-24 09:17:05.548015+00:00
[2025-05-24T09:17:53.656+0000] {standard_task_runner.py:60} INFO - Started process 1631 to run task
[2025-05-24T09:17:53.689+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_form_fills', 'manual__2025-05-24T09:17:05.548015+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpril7f_y2']
[2025-05-24T09:17:53.732+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask validate_form_fills
[2025-05-24T09:17:54.592+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_form_fills manual__2025-05-24T09:17:05.548015+00:00 [running]> on host e6492150ec46
[2025-05-24T09:17:55.849+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_form_fills' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T09:17:05.548015+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T09:17:05.548015+00:00'
[2025-05-24T09:17:55.867+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Validate Form Fills
[2025-05-24T09:17:56.774+0000] {metadata.py:138} INFO - üß™ DQ Check logged: form_fills_2025-05-24.parquet | schema_format = FAIL
[2025-05-24T09:17:58.475+0000] {metadata.py:138} INFO - üß™ DQ Check logged: form_fills_2025-05-24.parquet | file-level = FAIL
[2025-05-24T09:17:58.494+0000] {data_validation.py:31} WARNING - Quarantining invalid rows for: form_fills_2025-05-24.parquet
[2025-05-24T09:17:59.260+0000] {metadata.py:158} INFO - üîë Logged DQ signature for form_fills_2025-05-24.parquet: 
[2025-05-24T09:17:59.691+0000] {metadata.py:138} INFO - üß™ DQ Check logged: form_fills_2025-05-24.parquet | form_fills = FAIL
[2025-05-24T09:17:59.883+0000] {metadata.py:107} INFO - üìù Logged stage 'validated' for form_fills_2025-05-24.parquet at 2025-05-24T09:17:59.718688
[2025-05-24T09:17:59.902+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T09:17:59.926+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Validate Form Fills
[2025-05-24T09:17:59.932+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T09:18:00.007+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_form_fills, execution_date=20250524T091705, start_date=20250524T091753, end_date=20250524T091800
[2025-05-24T09:18:00.127+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T09:18:00.201+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
