[2025-05-25T16:27:30.984+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.validate_facts.validate_contacts manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T16:27:31.229+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_marketing_data_pipeline.validate_facts.validate_contacts manual__2025-05-25T16:25:47.685943+00:00 [queued]>
[2025-05-25T16:27:31.422+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-25T16:27:31.681+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_facts.validate_contacts> on 2025-05-25 16:25:47.685943+00:00
[2025-05-25T16:27:31.867+0000] {standard_task_runner.py:60} INFO - Started process 15974 to run task
[2025-05-25T16:27:31.901+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_marketing_data_pipeline', 'validate_facts.validate_contacts', 'manual__2025-05-25T16:25:47.685943+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6y_ta8di']
[2025-05-25T16:27:32.177+0000] {standard_task_runner.py:88} INFO - Job 116: Subtask validate_facts.validate_contacts
[2025-05-25T16:27:32.732+0000] {task_command.py:423} INFO - Running <TaskInstance: final_marketing_data_pipeline.validate_facts.validate_contacts manual__2025-05-25T16:25:47.685943+00:00 [running]> on host fe289fe396bd
[2025-05-25T16:27:33.877+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='final_marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_facts.validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T16:25:47.685943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T16:25:47.685943+00:00'
[2025-05-25T16:27:33.881+0000] {test.py:39} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-25T16:27:34.250+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | schema_format = PASS
[2025-05-25T16:27:34.559+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | freshness = PASS
[2025-05-25T16:27:37.788+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | row_count = PASS
[2025-05-25T16:27:37.977+0000] {data_validation.py:127} INFO - Valid Data for contacts_2025-05-25.csv created in /opt/***/data/validated_data
[2025-05-25T16:27:38.067+0000] {data_validation.py:142} INFO - Removed /opt/***/data/raw_data/contacts_2025-05-25.csv from raw_data folder
[2025-05-25T16:27:38.260+0000] {metadata.py:164} INFO - üîë Logged DQ signature for contacts_2025-05-25.csv: 
[2025-05-25T16:27:39.102+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-25.csv | contacts = PASS
[2025-05-25T16:27:39.370+0000] {metadata.py:109} INFO - üìù Logged stage 'validated' for contacts_2025-05-25.csv at 2025-05-25T16:27:39.127731
[2025-05-25T16:27:39.377+0000] {utils.py:55} INFO - task_metrics
[2025-05-25T16:27:39.383+0000] {test.py:41} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-25T16:27:39.389+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-25T16:27:39.428+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=final_marketing_data_pipeline, task_id=validate_facts.validate_contacts, execution_date=20250525T162547, start_date=20250525T162731, end_date=20250525T162739
[2025-05-25T16:27:39.474+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-25T16:27:39.590+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
